<?php

namespace App\Entity;

use App\Entity\BankAccount;
use App\Entity\BaseUser;
use App\Entity\ContegoScore;
use App\Entity\Document;
use App\Entity\Enum\KycReviewStatus;
use App\Entity\Enum\ScaStatus;
use App\Entity\Enum\UserStatus;
use App\Entity\Enum\WalletUserVersion;
use App\Entity\Investment;
use App\Entity\KycProfile;
use App\Entity\KycReport;
use App\Entity\KycReview;
use App\Entity\OnboardingProfile;
use App\Entity\Traits\TimestampableEntity;
use App\Entity\Wallet;
use App\Repository\UserRepository;
use App\Service\Util;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\Criteria;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use JMS\Serializer\Annotation as JMS;
use Scheb\TwoFactorBundle\Model\Email\TwoFactorInterface as EmailTwoFactorInterface;
use Scheb\TwoFactorBundle\Model\PreferredProviderInterface;
use Scheb\TwoFactorBundle\Model\Totp\TotpConfiguration;
use Scheb\TwoFactorBundle\Model\Totp\TotpConfigurationInterface;
use Scheb\TwoFactorBundle\Model\Totp\TwoFactorInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 *
 */
#[JMS\ExclusionPolicy('all')]
#[ORM\Table(name: 'users')]
#[ORM\Entity(repositoryClass: UserRepository::class)]
// ForDBAL4 #[Gedmo\Loggable]
class User extends BaseUser implements
    \JsonSerializable,
    TwoFactorInterface,
    EmailTwoFactorInterface,
    PreferredProviderInterface,
    PasswordAuthenticatedUserInterface
{
    use TimestampableEntity;

    /**
     *
     * Generated by user maker
     * Some fields comment out until FOSUserBundle has been deprecated
     *
     */
    /**
     */
    #[JMS\Expose]
    #[JMS\Groups(['minimum', 'standard', 'admin'])]
    #[ORM\Id]
    #[ORM\Column(type: 'integer')]
    #[ORM\GeneratedValue(strategy: 'AUTO')]
    protected $id;

    // protected $username;
    // protected $roles = [];
    // protected $password;
    /**
     *
     * Original properties
     *
     */
    /**
     * MIFID status
     *
     * @var int
     */
    #[ORM\Column(type: 'integer', nullable: true, options: ['default' => 0])]
    // ForDBAL4 #[Gedmo\Versioned]
    protected $ob_mifid = 0;

    /**
     * @var int
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[JMS\SerializedName('obStep')]
    #[ORM\Column(type: 'integer', nullable: true, options: ['default' => 0])]
    // ForDBAL4 #[Gedmo\Versioned]
    protected $ob_step = 0;

    /**
     * @var string
     */
    #[JMS\Expose]
    #[JMS\Groups(['standard', 'admin'])]
    #[JMS\SerializedName('firstName')]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $firstname;

    /**
     * @var string
     */
    #[JMS\Expose]
    #[JMS\Groups(['standard', 'admin'])]
    #[JMS\SerializedName('lastName')]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $lastname;

    /**
     * @var string $gender
     */
    #[JMS\Expose]
    #[JMS\Groups(['standard', 'admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $gender;

    /**
     * @var string $type
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $type;

    /**
     * @var \DateTime $lastLoginAt
     */
    #[ORM\Column(type: 'datetime', nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $lastLoginAt;

    /**
     * @var boolean $setPasswdExpiry
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(type: 'boolean', nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $setPasswdExpiry;

    /**
     * @var string $middlename
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $middlename;

    /**
     * @var string $honoricPrefix
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $honoricPrefix;

    /**
     * @var string $honoricSuffix
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $honoricSuffix;

    /**
     * @var string $jobTitle
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $jobTitle;

    /**
     * @var string $location
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $location;

    /**
     * @var string $nationality
     */
    #[JMS\Expose]
    #[JMS\Groups(['standard', 'admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $nationality;

    /**
     * @var string $mobile
     */
    #[JMS\Expose]
    #[JMS\Groups(['standard', 'admin'])]
    #[JMS\SerializedName('mobilePhone')]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $mobile;

    /**
     * @var string $phone1
     */
    #[JMS\Expose]
    #[JMS\Groups(['standard', 'admin'])]
    #[JMS\SerializedName('phone')]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $phone1;

    /**
     * @var string $phone2
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $phone2;

    /**
     * @var string $birthCountry
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $birthCountry;

    /**
     * @var \DateTime $birthDate
     */
    #[JMS\Expose]
    #[JMS\Groups(['standard', 'admin'])]
    #[JMS\SerializedName('dateOfBirth')]
    #[ORM\Column(type: 'datetime', nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $birthDate;

    /**
     * @var string $birthPlace
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $birthPlace;

    /**
     * @var string $drivingLicenseNo
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $drivingLicenseNo;

    /**
     * @var string $passportNumber
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $passportNumber;

    /**
     * @var string $passportCountry
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $passportCountry;

    /**
     * @var \DateTime $passportExpiry
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(type: 'datetime', nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $passportExpiry;

    /**
     * @var string $incomeRange
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $incomeRange;

    /**
     * @var Document
     */
    #[ORM\OneToOne(targetEntity: 'App\Entity\Document')]
    // ForDBAL4 #[Gedmo\Versioned]
    private $image;

    /**
     * @var string
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $mangoPayUserId;

    /**
     * @var string
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $mangoPayWalletId;

    /**
     * @var int $visibility
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(type: 'integer', nullable: false, options: ['default' => 0])]
    // ForDBAL4 #[Gedmo\Versioned]
    private $visibility = 0;

    /**
     * @var int $isVIP
     */
    #[JMS\Expose]
    #[JMS\Groups(['standard', 'admin'])]
    #[ORM\Column(type: 'integer', nullable: false, options: ['default' => 0])]
    // ForDBAL4 #[Gedmo\Versioned]
    private $isVIP = 0;

    /**
     * @var string $occupation
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(type: 'string', nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $occupation = 1;

    /**
     * @var string $additionalType
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(type: 'string', nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $additionalType;

    /**
     * @var string $additionalName
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(type: 'string', nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $additionalName;

    /**
     * @var string $affiliateCode
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $affiliateCode;

    /**
     * @var string $biography
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $biography;

    /**
     * @var string $externalReferenceId
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $externalReferenceId;

    /**
     * @var string $referralCode
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $referralCode;

    /**
     * @var string $sector
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $sector;

    /**
     * @var string $tagline
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $tagline;

    /**
     * @var string $taxId
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $taxId;

    /**
     * @var \DateTime $timezone
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(type: 'datetime', nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $timezone;

    /**
     * @var string $website
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\Column(nullable: true)]
    // ForDBAL4 #[Gedmo\Versioned]
    private $website;

    /**
     * @var bool
     * potentially deprecated or redundant
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[JMS\SerializedName('termServiceAccepted')]
    #[ORM\Column(nullable: true, options: ['default' => false])]
    // ForDBAL4 #[Gedmo\Versioned]
    private bool $term_service_accepted = false;

    /**
     * @var int
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[JMS\SerializedName('gdprAccepted')]
    #[ORM\Column(type: 'integer', nullable: false, options: ['default' => 0])]
    // ForDBAL4 #[Gedmo\Versioned]
    private $gdpr_accepted = 0;

    #[ORM\Column(type: 'integer', enumType: WalletUserVersion::class, options: [
        'default' => WalletUserVersion::Original,
    ])]
    private WalletUserVersion $walletUserVersion =
        WalletUserVersion::UserCategoryUpdate;

    /**
     *
     * Relations
     *
     */
    /**
     * @var \Doctrine\Common\Collections\ArrayCollection
     * @var $addresses
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\OneToMany(
        targetEntity: 'Address',
        mappedBy: 'user',
        cascade: ['persist', 'remove'],
        orphanRemoval: true,
    )]
    private $addresses;

    /**
     * @var \Doctrine\Common\Collections\ArrayCollection
     */
    #[ORM\OneToMany(targetEntity: 'App\Entity\AssetMember', mappedBy: 'user')]
    private $assets;

    /**
     * @var \Doctrine\Common\Collections\ArrayCollection
     * @var $communications
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\OneToMany(
        targetEntity: 'Communication',
        mappedBy: 'user',
        cascade: ['persist', 'remove'],
        orphanRemoval: true,
    )]
    private $communications;

    /**
     * @var ContegoScore $contego_score
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[JMS\SerializedName('contegoScore')]
    #[ORM\OneToOne(
        targetEntity: 'App\Entity\ContegoScore',
        inversedBy: 'user',
        cascade: ['persist'],
    )]
    // ForDBAL4 #[Gedmo\Versioned]
    private $contego_score;

    /**
     * @var \Doctrine\Common\Collections\ArrayCollection
     */
    #[ORM\OneToMany(
        targetEntity: 'UserClient',
        mappedBy: 'user',
        cascade: ['persist', 'remove'],
    )]
    private $clients;

    /**
     * @var Company
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\OneToOne(
        targetEntity: 'App\Entity\Company',
        inversedBy: 'user',
        cascade: ['persist'],
    )]
    // ForDBAL4 #[Gedmo\Versioned]
    private $company;

    /**
     * @var \Doctrine\Common\Collections\ArrayCollection
     * @var $customFields
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\OneToMany(
        targetEntity: 'UserCustomFields',
        mappedBy: 'user',
        cascade: ['persist'],
        orphanRemoval: true,
    )]
    private $customFields;

    /**
     * @var \Doctrine\Common\Collections\ArrayCollection
     *
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\OneToMany(
        targetEntity: 'App\Entity\UserDocument',
        mappedBy: 'user',
        cascade: ['persist', 'remove'],
    )]
    #[ORM\OrderBy(['createdAt' => 'DESC', 'id' => 'DESC'])]
    private $documents;

    /**
     * @var \Doctrine\Common\Collections\ArrayCollection
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\OneToMany(targetEntity: 'App\Entity\Investment', mappedBy: 'user')]
    private $investments;

    /**
     * @var Investor $investor
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\OneToOne(
        targetEntity: 'App\Entity\Investor',
        inversedBy: 'user',
        cascade: ['persist'],
    )]
    // ForDBAL4 #[Gedmo\Versioned]
    private $investor;

    /**
     * @var ArrayCollection
     */
    #[ORM\OneToMany(
        targetEntity: 'App\Entity\UserLog',
        mappedBy: 'user',
        cascade: ['all'],
        orphanRemoval: true,
    )]
    protected $logs;

    /**
     * @var User
     */
    #[ORM\ManyToOne(targetEntity: 'User', inversedBy: 'managedUsers')]
    #[ORM\JoinColumn(
        name: 'managedBy_id',
        referencedColumnName: 'id',
        nullable: true,
        onDelete: 'SET NULL',
    )]
    private $managedBy;

    /**
     * @var UserSecurity
     */
    #[ORM\OneToOne(
        targetEntity: 'UserSecurity',
        inversedBy: 'user',
        cascade: ['persist'],
    )]
    private $security;

    /**
     * @var \Doctrine\Common\Collections\ArrayCollection
     */
    #[ORM\OneToMany(
        targetEntity: 'User',
        mappedBy: 'managedBy',
        cascade: ['persist', 'remove'],
    )]
    private $managedUsers;

    /**
     * @var Status
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\OneToOne(
        targetEntity: 'App\Entity\Status',
        cascade: ['all'],
        inversedBy: 'user',
    )]
    // ForDBAL4 #[Gedmo\Versioned]
    protected $status;

    /**
     * @var Wallet $wallet
     */
    #[JMS\Expose]
    #[JMS\Groups(['admin'])]
    #[ORM\OneToOne(
        targetEntity: 'App\Entity\Wallet',
        inversedBy: 'user',
        cascade: ['persist'],
    )]
    // ForDBAL4 #[Gedmo\Versioned]
    private $wallet;

    #[ORM\OneToMany(
        mappedBy: 'user',
        targetEntity: BankAccount::class,
        orphanRemoval: true,
    )]
    #[ORM\OrderBy(['id' => 'DESC'])]
    private Collection $bankAccounts;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?KycProfile $kycProfile = null;

    #[ORM\OneToMany(
        mappedBy: 'subject',
        targetEntity: KycReport::class,
        orphanRemoval: true,
    )]
    private Collection $kycReports;

    #[ORM\OneToMany(
        mappedBy: 'subject',
        targetEntity: KycReview::class,
        orphanRemoval: true,
    )]
    private Collection $kycReviews;

    #[ORM\OneToOne(inversedBy: 'user', cascade: ['persist', 'remove'])]
    private ?OnboardingProfile $onboardingProfile = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTime $scaEnrolledAt = null;

    #[ORM\Column(enumType: ScaStatus::class, options: [
        'default' => ScaStatus::Inactive,
    ])]
    private ScaStatus $scaStatus = ScaStatus::Inactive;

    #[ORM\Column(nullable: true)]
    private ?\DateTime $bankAccountsSyncedAt = null;

    /**
     * @var Collection<int, UserStatusLog>
     */
    #[ORM\OneToMany(
        targetEntity: UserStatusLog::class,
        mappedBy: 'user',
        orphanRemoval: true,
        cascade: ['persist'],
    )]
    #[ORM\OrderBy(['occuredAt' => 'ASC', 'id' => 'ASC'])]
    private Collection $statusLogs;

    /**
     * @var Collection<int, TradeOrder>
     */
    #[ORM\OneToMany(
        mappedBy: 'user',
        targetEntity: TradeOrder::class,
        orphanRemoval: true,
    )]
    private Collection $tradeOrders;

    public function __construct(?\DateTime $createdAt = null)
    {
        parent::__construct();

        $this->setGDPRAccepted(0);
        $this->setTermServiceAccepted(0);

        $this->status = new Status();
        $this->security = new UserSecurity();
        $this->investor = new Investor();
        $this->company = new Company();
        $this->kycProfile = new KycProfile();
        $this->addresses = new ArrayCollection();
        $this->documents = new ArrayCollection();
        $this->assets = new ArrayCollection();
        $this->customFields = new ArrayCollection();
        $this->communications = new ArrayCollection();
        $this->logs = new ArrayCollection();
        $this->managedUsers = new ArrayCollection();
        $this->enabled = true;
        $this->bankAccounts = new ArrayCollection();
        $this->kycReports = new ArrayCollection();
        $this->kycReviews = new ArrayCollection();
        $this->statusLogs = new ArrayCollection();

        // Setting custom createdAt is mainly for fixtures
        $this->addStatusLog(
            new UserStatusLog(occuredAt: $createdAt ?? new \DateTime()),
        );

        // Don't initialise OnboardingProfile in constructor
        // Due to how assessmentPassed needs to be marked as passed
        // for older users who registered before full PS22/10 rules
        // $this->onboardingProfile = new OnboardingProfile();
        $this->tradeOrders = new ArrayCollection();
    }

    /**
     *
     * Generated by user maker
     *
     */

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    /**
     * The public representation of the user (e.g. a username, an email address, etc.)
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    // public function setUsername(string $username): self
    // {
    //     $this->username = $username;

    //     return $this;
    // }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    // public function setPassword(string $password): self
    // {
    //     $this->password = $password;

    //     return $this;
    // }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    /**
     *
     * Core/Simple getter, setters, issers, hassers
     *
     */

    public function getAdditionalName(): ?string
    {
        return $this->additionalName;
    }

    public function setAdditionalName(?string $additionalName): self
    {
        $this->additionalName = $additionalName;
        return $this;
    }

    public function getAdditionalType(): ?string
    {
        return $this->additionalType;
    }

    public function setAdditionalType(?string $additionalType): self
    {
        $this->additionalType = $additionalType;
        return $this;
    }

    public function getAffiliateCode(): ?string
    {
        return $this->affiliateCode;
    }

    public function setAffiliateCode(?string $affiliateCode): self
    {
        $this->affiliateCode = $affiliateCode;
        return $this;
    }

    public function getBiography(): ?string
    {
        return $this->biography;
    }

    public function setBiography(?string $biography): self
    {
        $this->biography = $biography;
        return $this;
    }

    public function getBirthCountry(): ?string
    {
        return $this->birthCountry;
    }

    public function setBirthCountry(?string $birthCountry): self
    {
        $this->birthCountry = $birthCountry;

        return $this;
    }

    public function getBirthDate(): ?\DateTime
    {
        return $this->birthDate;
    }

    public function setBirthDate(?\DateTime $birthDate): self
    {
        $this->birthDate = $birthDate;
        return $this;
    }

    public function getBirthPlace(): ?string
    {
        return $this->birthPlace;
    }

    public function setBirthPlace(?string $birthPlace): self
    {
        $this->birthPlace = $birthPlace;
        return $this;
    }

    public function getDrivingLicenseNo(): ?string
    {
        return $this->drivingLicenseNo;
    }

    public function setDrivingLicenseNo(?string $drivingLicenseNo): self
    {
        $this->drivingLicenseNo = $drivingLicenseNo;

        return $this;
    }

    public function getExternalReferenceId(): ?string
    {
        return $this->externalReferenceId;
    }

    public function setExternalReferenceId(?string $externalReferenceId): self
    {
        $this->externalReferenceId = $externalReferenceId;
        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;
        return $this;
    }

    public function getGender(): ?string
    {
        return $this->gender;
    }

    public function setGender(?string $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getHonoricPrefix(): ?string
    {
        return $this->honoricPrefix;
    }

    public function setHonoricPrefix(?string $honoricPrefix): self
    {
        $this->honoricPrefix = $honoricPrefix;
        return $this;
    }

    public function getHonoricSuffix(): ?string
    {
        return $this->honoricSuffix;
    }

    public function setHonoricSuffix(?string $honoricSuffix): self
    {
        $this->honoricSuffix = $honoricSuffix;
        return $this;
    }

    public function getImage(): ?Document
    {
        return $this->image;
    }

    public function setImage(?Document $image = null): self
    {
        $this->image = $image;
        return $this;
    }

    public function getIncomeRange(): ?string
    {
        return $this->incomeRange;
    }

    public function setIncomeRange(?string $incomeRange): self
    {
        $this->incomeRange = $incomeRange;
        return $this;
    }

    public function isGDPRAccepted(): int
    {
        return $this->gdpr_accepted;
    }

    public function setGDPRAccepted(int $gdpr_accepted): self
    {
        $this->gdpr_accepted = $gdpr_accepted;
        return $this;
    }

    public function isTermServiceAccepted(): ?bool
    {
        return $this->term_service_accepted;
    }

    public function setTermServiceAccepted(?bool $term_service_accepted): self
    {
        $this->term_service_accepted = $term_service_accepted;
        return $this;
    }

    public function getisVIP(): ?int
    {
        return $this->isVIP;
    }

    public function setisVIP(?int $isVIP): self
    {
        $this->isVIP = $isVIP;
        return $this;
    }

    public function getJobTitle(): ?string
    {
        return $this->jobTitle;
    }

    public function setJobTitle(?string $jobTitle): self
    {
        $this->jobTitle = $jobTitle;
        return $this;
    }

    public function getLastLoginAt(): ?\DateTime
    {
        return $this->lastLoginAt;
    }

    public function setLastLoginAt(?\DateTime $lastLoginAt): self
    {
        $this->lastLoginAt = $lastLoginAt;
        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;
        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    public function setLocation(?string $location): self
    {
        $this->location = $location;
        return $this;
    }

    public function getMangoPayUserId(): ?string
    {
        return $this->mangoPayUserId;
    }

    public function setMangoPayUserId(?string $mangoPayUserId): self
    {
        $this->mangoPayUserId = $mangoPayUserId;
        return $this;
    }

    public function getMangoPayWalletId(): ?string
    {
        return $this->mangoPayWalletId;
    }

    public function setMangoPayWalletId(?string $mangoPayWalletId): self
    {
        $this->mangoPayWalletId = $mangoPayWalletId;
        return $this;
    }

    public function getMiddlename(): ?string
    {
        return $this->middlename;
    }

    public function setMiddlename(?string $middlename): self
    {
        $this->middlename = $middlename;

        return $this;
    }

    public function getMIFIDStatus(): ?int
    {
        return $this->ob_mifid;
    }

    public function setMIFIDStatus(?int $ob_mifid): self
    {
        $this->ob_mifid = $ob_mifid;
        return $this;
    }

    public function getMobile(): ?string
    {
        return $this->mobile;
    }

    public function setMobile(?string $mobile): self
    {
        $this->mobile = $mobile;
        return $this;
    }

    public function getNationality(): ?string
    {
        return $this->nationality;
    }

    public function setNationality(?string $nationality): self
    {
        $this->nationality = $nationality;
        return $this;
    }

    public function getOBStep(): ?int
    {
        return $this->ob_step;
    }

    public function setOBStep(?int $ob_step): self
    {
        $this->ob_step = $ob_step;
        return $this;
    }

    public function getOccupation(): ?string
    {
        return $this->occupation;
    }

    public function setOccupation(?string $occupation): self
    {
        $this->occupation = $occupation;
        return $this;
    }

    public function getPassportCountry(): ?string
    {
        return $this->passportCountry;
    }

    public function setPassportCountry(?string $passportCountry): self
    {
        $this->passportCountry = $passportCountry;
        return $this;
    }

    public function getPassportExpiry(): ?\DateTime
    {
        return $this->passportExpiry;
    }

    public function setPassportExpiry(?\DateTime $passportExpiry): self
    {
        $this->passportExpiry = $passportExpiry;

        return $this;
    }

    public function getPassportNumber(): ?string
    {
        return $this->passportNumber;
    }

    public function setPassportNumber(?string $passportNumber): self
    {
        $this->passportNumber = $passportNumber;
        return $this;
    }

    public function getPhone1(): ?string
    {
        return $this->phone1;
    }

    public function setPhone1(?string $phone1): self
    {
        $this->phone1 = $phone1;
        return $this;
    }

    public function getPhone2(): ?string
    {
        return $this->phone2;
    }

    public function setPhone2(?string $phone2): self
    {
        $this->phone2 = $phone2;
        return $this;
    }

    public function getReferralCode(): ?string
    {
        return $this->referralCode;
    }

    public function setReferralCode(?string $referralCode): self
    {
        $this->referralCode = $referralCode;
        return $this;
    }

    public function getSector(): ?string
    {
        return $this->sector;
    }

    public function setSector(?string $sector): self
    {
        $this->sector = $sector;
        return $this;
    }

    public function getSetPasswdExpiry(): ?bool
    {
        return $this->setPasswdExpiry;
    }

    public function setSetPasswdExpiry(?bool $setPasswdExpiry): self
    {
        $this->setPasswdExpiry = $setPasswdExpiry;
        return $this;
    }

    public function getTagline(): ?string
    {
        return $this->tagline;
    }

    public function setTagline(?string $tagline): self
    {
        $this->tagline = $tagline;
        return $this;
    }

    public function getTaxId(): ?string
    {
        return $this->taxId;
    }

    public function setTaxId(?string $taxId): self
    {
        $this->taxId = $taxId;
        return $this;
    }

    public function getTimezone(): ?\DateTime
    {
        return $this->timezone;
    }

    public function setTimezone(?\DateTime $timezone): self
    {
        $this->timezone = $timezone;
        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(?string $type): self
    {
        $this->type = $type;
        return $this;
    }

    public function getVisibility(): ?int
    {
        return $this->visibility;
    }

    public function setVisibility(?int $visibility): self
    {
        $this->visibility = $visibility;
        return $this;
    }

    public function getWebsite(): ?string
    {
        return $this->website;
    }

    public function setWebsite(?string $website): self
    {
        $this->website = $website;
        return $this;
    }

    public function isAMangoPayUser()
    {
        return !empty($this->mangoPayUserId);
    }

    public function getWalletUserVersion(): WalletUserVersion
    {
        return $this->walletUserVersion;
    }

    public function setWalletUserVersion(WalletUserVersion $walletUserVersion): self
    {
        $this->walletUserVersion = $walletUserVersion;

        return $this;
    }

    /**
     *
     * Relation getters and setters (relations that are one-to-one)
     *
     */

    public function getCompany(): ?\App\Entity\Company
    {
        return $this->company;
    }

    public function setCompany(?\App\Entity\Company $company = null): self
    {
        $company->setUser($this);
        $this->company = $company;
        return $this;
    }

    public function getContegoScore(): ?ContegoScore
    {
        return $this->contego_score;
    }

    public function setContegoScore(ContegoScore $contego_score): self
    {
        $this->contego_score = $contego_score;
        return $this;
    }

    public function getInvestor(): ?\App\Entity\Investor
    {
        return $this->investor;
    }

    public function setInvestor(?\App\Entity\Investor $investor = null): self
    {
        $this->investor = $investor;
        return $this;
    }

    public function getManagedBy(): ?\App\Entity\User
    {
        return $this->managedBy;
    }

    public function setManagedBy(?\App\Entity\User $managedBy): self
    {
        $this->managedBy = $managedBy;
        return $this;
    }

    public function getSecurity(): \App\Entity\UserSecurity
    {
        // backwards compatibility for users without a user_security entry
        // create the new UserSecurity like the constructor would
        return (
            $this->security ?? $this->setSecurity(
                new \App\Entity\UserSecurity(),
            )->getSecurity()
        );
    }

    public function setSecurity(\App\Entity\UserSecurity $security): self
    {
        $this->security = $security;
        return $this;
    }

    public function getStatus(): ?\App\Entity\Status
    {
        return $this->status;
    }

    public function setStatus(\App\Entity\Status $status): self
    {
        $this->status = $status;
        return $this;
    }

    public function getWallet(): ?Wallet
    {
        return $this->wallet;
    }

    public function setWallet(?Wallet $wallet = null): self
    {
        $this->wallet = $wallet;
        return $this;
    }

    /**
     *
     * Collections getters and setters (relations that are not one-to-one)
     *
     */

    public function getAddresses(): ?Collection
    {
        return $this->addresses;
    }

    public function addAddress(\App\Entity\Address $address): self
    {
        $address->setUser($this);
        $this->addresses[] = $address;
        return $this;
    }

    public function removeAddress(\App\Entity\Address $address): self
    {
        $this->addresses->removeElement($address);
        return $this;
    }

    public function getAssets(): ?Collection
    {
        return $this->assets;
    }

    public function addAssetMember(\App\Entity\AssetMember $assetMember): self
    {
        $assetMember->setUser($this);
        $this->assets[] = $assetMember;
        return $this;
    }

    public function getClients(): ArrayCollection
    {
        return $this->clients;
    }

    public function addClient(UserClient $client): self
    {
        $client->setUser($this);
        $this->clients[] = $client;
        return $this;
    }

    public function removeClient(UserClient $client): self
    {
        $this->clients->removeElement($client);
        return $this;
    }

    public function getCommunication(): ?Collection
    {
        return $this->communications;
    }

    public function addCommunication(\App\Entity\Communication $communications): self
    {
        $communications->setRecipient($this);
        $this->communications[] = $communications;
        return $this;
    }

    public function removeCommunication(\App\Entity\Communication $communications): self
    {
        $this->communications->removeElement($communications);
        return $this;
    }

    public function getCustomFields(): ?Collection
    {
        return $this->customFields;
    }

    public function addCustomField(\App\Entity\UserCustomFields $field): self
    {
        $field->setUser($this);
        $this->customFields[] = $field;

        return $this;
    }

    public function removeCustomField(\App\Entity\UserCustomFields $field): self
    {
        $this->customFields->removeElement($field);
        return $this;
    }

    public function getDocuments(): ?Collection
    {
        return $this->documents;
    }

    public function addDocument(\App\Entity\UserDocument $document): self
    {
        $document->setUser($this);
        $this->documents[] = $document;
        return $this;
    }

    public function removeDocument(\App\Entity\UserDocument $document): self
    {
        $this->documents->removeElement($document);
        return $this;
    }

    public function getInvestments(): ?Collection
    {
        return $this->investments;
    }

    public function addInvestment(Investment $investment): self
    {
        $investment->setUser($this);
        $this->investments[] = $investment;
        return $this;
    }

    public function getLogs(): ?Collection
    {
        return $this->logs;
    }

    public function addLog(\App\Entity\UserLog $log): self
    {
        $this->logs[] = $log;
        return $this;
    }

    public function removeLog(\App\Entity\UserLog $log): self
    {
        $this->logs->removeElement($log);
        return $this;
    }

    public function getManagedUsers(): ?Collection
    {
        return $this->managedUsers;
    }

    public function addManagedUser(\App\Entity\User $managedUser): self
    {
        $managedUser->setManagedBy($this);
        $this->managedUsers[] = $managedUser;
        return $this;
    }

    public function removeManagedUser(\App\Entity\User $managedUser): self
    {
        $this->managedUsers->removeElement($managedUser);
        return $this;
    }

    /**
     *
     * Relational getters and setters (direct access to one-to-one relations)
     *
     */

    /**
     * @param string $lifecycleStatus
     * @return $this
     */
    public function setLifecycleStatus($lifecycleStatus)
    {
        $this->status->setLifecycleStatus($lifecycleStatus);
        return $this;
    }

    /**
     * @return string
     */
    #[JMS\Expose]
    #[JMS\VirtualProperty]
    #[JMS\Groups(['standard'])]
    #[JMS\SerializedName('status')]
    public function getLifecycleStatus()
    {
        return $this->status->getLifecycleStatus();
    }

    /**
     * @param $comment string
     * @return $this
     */
    public function setLifecycleStatusComment($comment)
    {
        $this->status->setLifecycleStatusComment($comment);

        return $this;
    }

    /**
     * @return string
     */
    public function getLifecycleStatusComment()
    {
        return $this->status->getLifecycleStatusComment();
    }

    /**
     *
     * Interface implementations
     *
     */

    public function getPreferredTwoFactorProvider(): ?string
    {
        return $this->getSecurity()->getMfaPreference();
    }

    public function isTotpAuthenticationEnabled(): bool
    {
        // return $this->mfaKey ? true : false;
        // return $this->getSecurity()->getMfaTotp() == 1 ? true : false;
        if (!empty($this->getSecurity()) && $this->getSecurity()->getMfaTotp()) {
            return true;
        } else {
            return false;
        }
    }

    public function getTotpAuthenticationUsername(): string
    {
        return $this->username;
    }

    public function getTotpAuthenticationConfiguration(): TotpConfigurationInterface
    {
        /**
         * Could persist the other configuration options in the user entity to make it individual per user.
         * We'll only support Google Authenticator specs for TOTP for now
         * - SHA1 algorithm
         * - 30 second period
         * - 6 digit code
         */
        return new TotpConfiguration(
            $this->getSecurity()->getTotpKey(),
            TotpConfiguration::ALGORITHM_SHA1,
            30,
            6,
        );
    }

    public function isEmailAuthEnabled(): bool
    {
        if (!empty($this->getSecurity()) && $this->getSecurity()->getMfaEmail()) {
            return true;
        } else {
            return false;
        }
    }

    public function getEmailAuthRecipient(): string
    {
        return $this->email;
    }

    public function getEmailAuthCode(): string
    {
        return $this->getSecurity()->getEmailAuthCode();
    }

    public function setEmailAuthCode(string $authCode): void
    {
        $this->getSecurity()->setEmailAuthCode($authCode);
    }

    /**
     *
     * ALternative getters
     *
     */

    public function getFullname()
    {
        $parts = [];

        $parts[] = $this->firstname;

        $parts[] = $this->middlename;

        $parts[] = $this->lastname;

        return implode(' ', $parts);

        // return $this;
    }

    /**
     * Special getter to return the most recent address which is deemed the main/current address
     * @return Address
     */
    #[JMS\Expose]
    #[JMS\VirtualProperty]
    #[JMS\Groups(['standard'])]
    #[JMS\SerializedName('address')]
    public function getMainAddress()
    {
        if (isset($this->addresses)) {
            if (count($this->addresses) > 0) {
                $address = $this->getAddresses()->last();
                return $address;
            }
        }

        return new Address();
    }

    /**
     * Helper to return a proof of id document related to a user
     *
     * @return UserDocument|null
     */
    public function getProofOfIdDocument()
    {
        if (isset($this->documents)) {
            foreach ($this->documents->getIterator() as $i => $document) {
                $tag = $document->getDocument()->getTag();
                if ($tag == 'proof_of_identity') {
                    return $document;
                }
            }
        }
        return null;
    }

    /**
     * Helper to return a proof of address document related to a user
     *
     * @return UserDocument|null
     */
    public function getProofOfAddressDocument()
    {
        if (isset($this->documents)) {
            foreach ($this->documents->getIterator() as $i => $document) {
                $tag = $document->getDocument()->getTag();
                if ($tag == 'proof_of_address') {
                    return $document;
                }
            }
        }
        return null;
    }

    /**
     * set the isVIP and isAdmin elements
     *
     * @return array
     */
    private function getUserType($array_items)
    {
        $role = $this->isSuperAdmin() || $this->hasRole('ROLE_ADMIN');
        if ($role === true) {
            $array_items['is_admin'] = 1;
        }
        $array_items['is_vip'] = $this->isVIP;
        return $array_items;
    }

    /**
     *
     * Support methods
     *
     */

    /***
     * find
     *
     * @param $cf_key
     *
     * @return string
     */
    public function findCustomFieldValue($cf_key)
    {
        /** @var UserCustomFields $cf */
        foreach ($this->customFields as $cf) {
            if ($cf->getFieldKey() == $cf_key) {
                return $cf->getFieldValue();

                // break;
            }
        }
        return '';
    }

    public function findCustomField(string $key): ?UserCustomFields
    {
        /** @var UserCustomFields $cf */
        foreach ($this->customFields as $cf) {
            if ($cf->getFieldKey() == $key) {
                return $cf;
            }
        }
        return null;
    }

    /**
     * find the custom field and replaces it if different
     *
     * @param UserCustomFields $field
     * @param string $cf_key
     * @return bool
     *
     */
    public function findReplaceCustomField(UserCustomFields $field)
    {
        $found = false;
        /** @var UserCustomFields $cf */
        foreach ($this->customFields as $cf) {
            if ($cf->getFieldKey() == $field->getFieldKey()) {
                if ($cf->getFieldValue() != $field->getFieldValue()) {
                    $cf->setFieldValue($field->getFieldValue());
                }
                $found = true;
                break;
            }
        }

        if ($found == false) {
            $this->addCustomField($field);
        }

        return $found;
    }

    public function isCustomFatca(): bool
    {
        $ucf = $this->findCustomField('fatca');
        if ($ucf !== null) {
            return (bool) $ucf->getFieldValue();
        }
        return false;
    }

    public function getCustomCompanyApprovedOn(): ?string
    {
        $ucf = $this->findCustomField('companyApprovedOn');
        if ($ucf !== null) {
            return $ucf->getFieldValue();
        }
        return null;
    }

    /**
     *
     * Legacy views
     *
     */

    /**
     *
     * Generate the json for info fields
     * @return array
     */
    public function getCustomJson()
    {
        $result = [
            Util\Helper::convertInInfo('organization_name', $this->company->getName()),
            Util\Helper::convertInInfo('position', $this->company->getPosition()),
            Util\Helper::convertInInfo('income_range', $this->incomeRange),
            Util\Helper::convertInInfo('referral', $this->referralCode),

            Util\Helper::convertInInfo(
                'cxb_worth_investor',
                $this->investor->getCxbWorthInvestor(),
            ),
            Util\Helper::convertInInfo(
                'cxb_sophisticated_investor',
                $this->investor->getCxbSophisticatedInvestor(),
            ),
            Util\Helper::convertInInfo(
                'cxb_restricted_investor',
                $this->investor->getCxbRestrictedUser(),
            ),
            Util\Helper::convertInInfo(
                'cxb_ltd_company_investor',
                $this->investor->getCxbRestrictedUser(),
            ),
            Util\Helper::convertInInfo(
                'always_go_up',
                $this->investor->getAlwaysGoUp(),
            ),
            Util\Helper::convertInInfo(
                'income_every_month',
                $this->investor->getIncomeEveryMonth(),
            ),
            Util\Helper::convertInInfo('never_exit', $this->investor->getNeverExit()),
            Util\Helper::convertInInfo(
                'corporate_investor',
                $this->investor->getCorporateInvestor(),
            ),
            Util\Helper::convertInInfo(
                'custom.poi_file_id',
                $this->investor->getPoiFileId(),
            ),
            Util\Helper::convertInInfo('poi_file_id', $this->investor->getPoiFileId()),
            Util\Helper::convertInInfo(
                'words_of_your_own',
                $this->investor->getWordsOfOwn(),
            ),

            Util\Helper::convertInInfo(
                'company_beneficial_owners',
                $this->company->getBeneficialOwners(),
            ),
            Util\Helper::convertInInfo(
                'company_directors',
                $this->company->getDirectors(),
            ),
            Util\Helper::convertInInfo(
                'company_website',
                $this->company->getCompanyWebsite(),
            ),
            Util\Helper::convertInInfo(
                'operating_address',
                $this->company->getOperatingAddress(),
            ),
            Util\Helper::convertInInfo(
                'operating_postcode',
                $this->company->getOperatingPostCode(),
            ),
            Util\Helper::convertInInfo(
                'reg_address_1',
                $this->company->getRegAddress1(),
            ),
            Util\Helper::convertInInfo(
                'reg_address_2',
                $this->company->getRegAddress2(),
            ),
            Util\Helper::convertInInfo(
                'reg_address_3',
                $this->company->getRegAddress3(),
            ),
            Util\Helper::convertInInfo('reg_country', $this->company->getRegCountry()),
            Util\Helper::convertInInfo('post_code', $this->company->getPostCode()),
        ];
        //add the custom fields
        /** @var UserCustomFields $cf */
        foreach ($this->customFields as $cf) {
            $result[] = Util\Helper::convertInInfo(
                $cf->getFieldKey(),
                $cf->getFieldValue(),
            );
        }
        return $result;
    }

    /**
     * Internal view of User, will be used on authenticated calls
     *
     * @return array
     */
    public function jsonInternal()
    {
        $array_items = [
            //@todo lots of mssing fields... need to fix this
            'image' => null, //'missing field'
            'additional_name' => $this->additionalName,
            'additional_type' => $this->additionalType,
            'affiliate_code' => $this->affiliateCode,
            'biography' => $this->biography,
            'birth_country' => Util\Helper::getCountryCode($this->birthCountry),
            'birth_date' => Util\Helper::formatDate($this->birthDate),
            'birth_place' => $this->birthPlace,
            'driving_license_number' => $this->getDrivingLicenseNo(),
            'email' => $this->email,
            'username' => $this->username,
            'external_reference_id' => $this->externalReferenceId,
            'family_name' => $this->lastname,
            'full_name' => $this->getFullname(),
            'gender' => $this->gender,
            'given_name' => $this->firstname,
            'honorific_prefix' => $this->honoricPrefix,
            'honorific_suffix' => $this->honoricSuffix,
            'id' => $this->getId(),

            'income_range' => $this->incomeRange,

            'job_title' => $this->jobTitle,
            'last_login_at' => $this->lastLoginAt,
            'location' => $this->location,
            // 'mangopay_card_id' => 'missing field',
            'mangopay_user_id' => $this->mangoPayUserId,
            'mangopay_wallet_id' => $this->mangoPayWalletId,
            'has_mangopay_wallet_id' => !empty($this->mangoPayWalletId),

            'nationality' => Util\Helper::getCountryCode($this->nationality),
            'passport_country' => Util\Helper::getCountryCode($this->passportCountry),

            // 'passport_expiry' => Util\Helper::formatDate($this->passportExpiry),
            // 'passport_number' => $this->passportNumber,
            // 'password_expired' => $this->passportExpiry,
            'phone_1' => $this->phone1,
            'phone_2' => $this->phone2,
            'mobile' => $this->mobile,

            'referral_code' => $this->referralCode,

            'sector' => $this->sector,
            'tagline' => $this->tagline,

            'tax_id' => $this->taxId,
            'time_zone' => $this->timezone,
            'visibility' => $this->visibility,
            'web_site' => $this->website,

            /* relationships */
            'address' => $this->getMainAddress(),
            'bank_accounts' => null,
            'info' => $this->getCustomJson(),
            'documents' => $this->documents->getValues(),
            'organizations' => $this->assets->getValues(),

            'phone_verified' => 0, //$this-> , //missing field
            'email_verified' => $this->status->getIsEmailValidated(),
            'has_been_approved' => $this->status->getIsApproved(),
            'has_been_blocked' => $this->status->getIsBlocked(),
            'registration_complete' => $this->status->getIsRegCompleted(),
            'term_service_accepted' => $this->term_service_accepted,
            'gdpr_accepted' => $this->gdpr_accepted,
            'ob_step' => $this->getOBStep(),
            'mifid_status' => $this->getMIFIDStatus(),

            'onboarding_profile' => $this->getOnboardingProfile(),
            'open_kyc_reviews' => $this->getKycReviewsNeedingAction()->getValues(),
            'sca_status' => $this->getScaStatus(),
            'sca_enrolled_at' => Util\Helper::formatDate($this->getScaEnrolledAt()),
            'bank_accounts_synced_at' => Util\Helper::formatDate($this->getBankAccountsSyncedAt()),
            'account_status' => $this->getCurrentStatus(),

            /* audit */
            'created_at' => Util\Helper::formatDate($this->createdAt),
            'updated_at' => Util\Helper::formatDate($this->updatedAt),
        ];
        //add the admin/vip status
        $array_items = $this->getUserType($array_items);
        return $array_items;
    }

    /**
     * Public view of User , sensitive fields have been removed
     *
     * @return array
     */
    public function jsonSerialize(): mixed
    {
        $array_items = [
            'image' => null, //'missing field'
            'additional_name' => $this->additionalName,
            'additional_type' => $this->additionalType,
            'affiliate_code' => $this->affiliateCode,

            'email' => $this->email,
            'username' => $this->username,
            'external_reference_id' => $this->externalReferenceId,
            'family_name' => $this->lastname,
            'full_name' => $this->getFullname(),

            'given_name' => $this->firstname,
            'honorific_prefix' => $this->honoricPrefix,
            'honorific_suffix' => $this->honoricSuffix,
            'id' => $this->getId(),

            'job_title' => $this->jobTitle,
            'last_login_at' => $this->lastLoginAt,
            'location' => $this->location,
            'referral_code' => $this->referralCode,
            'address' => $this->getMainAddress(),

            'sector' => $this->sector,
            'tagline' => $this->tagline,
            'visibility' => $this->visibility,

            'phone_verified' => 0, //$this-> , //missing field
            'email_verified' => $this->status->getIsEmailValidated(),
            'has_been_approved' => $this->status->getIsApproved(),
            'has_been_blocked' => $this->status->getIsBlocked(),
            'registration_complete' => $this->status->getIsRegCompleted(),
            'term_service_accepted' => $this->term_service_accepted,
            'gdpr_accepted' => $this->gdpr_accepted,
            'ob_step' => $this->getOBStep(),
            'mifid_status' => $this->getMIFIDStatus(),

            /* audit */
            'created_at' => Util\Helper::formatDate($this->createdAt),
            'updated_at' => Util\Helper::formatDate($this->updatedAt),
        ];
        //add the admin/vip status
        $array_items = $this->getUserType($array_items);
        return $array_items;
    }

    /**
     * Salesforce compatible view of user - with custom sf field names
     *
     * @return array
     */
    public function getSalesforceJson(bool $apiV2User = false)
    {
        if ($apiV2User) {
            $mobile = $this->mobile;
        } else {
            $mobile = $this->phone2;
        }

        $address_obj = $this->getMainAddress(); // returns Address object
        $array_items = [
            'id__c' => $this->id,
            'FirstName' => $this->firstname,
            'LastName' => $this->lastname,
            'Email' => $this->email,
            'MobilePhone' => $mobile, // BEWARE - due to how onboarding is implemented, we use phone2 not mobile
            'Phone' => $this->phone1,
            'username__c' => $this->getUsername(),
            'IsEmailValidated__c' => $this->status->getIsEmailValidated(),
            'gender__c' => $this->gender,
            'honoricPrefix__c' => $this->honoricPrefix,
            'jobTitle__c' => $this->jobTitle,
            'address1__c' => $address_obj->getAddress1(),
            'address2__c' => $address_obj->getAddress2(),
            'address3__c' => $address_obj->getAddress3(),
            'city__c' => $address_obj->getCity(),
            'postCode__c' => $address_obj->getPostCode(),
            'country__c' => $address_obj->getCountry(),
            'nationality__c' => $this->nationality,
            'birthDate__c' => Util\Helper::formatDate($this->birthDate),
            // 'mangoPayUserId__c' => $this->mangoPayUserId,
            // 'mangoPayWalletId__c' => $this->mangoPayWalletId,
            'isVIP__c' => $this->isVIP,
            //'occupation__c' => $user['email_verified'],
            // 'referralCode__c' => $this->referralCode,
            'gdpr_accepted__c' => $this->gdpr_accepted,
            'cxbWorthInvestor__c' => $this->investor->getCxbWorthInvestor() ?? false,
            'cxbSophisticatedInvestor__c' =>
                $this->investor->getCxbSophisticatedInvestor() ?? false,
            'cxbRestrictedUser__c' => $this->investor->getCxbRestrictedUser() ?? false,
            'corporateInvestor__c' => $this->investor->getCorporateInvestor() ?? false,
            'wordsOfOwn__c' => substr($this->investor->getWordsOfOwn(), 0, 255),
            'IsApproved__c' => $this->status->getIsApproved(),
            'isRegCompleted__c' => $this->status->getIsRegCompleted(),
            'isBlocked__c' => $this->status->getIsBlocked(),
            'joinDate__c' => Util\Helper::formatDate($this->createdAt),
            'last_login__c' => Util\Helper::formatDate($this->getLastLogin()),
        ];

        $array_items = Util\Helper::convertArrayBoolsToInt($array_items);
        return $array_items;
    }

    /**
     * @return Collection<int, BankAccount>
     */
    public function getBankAccounts(): Collection
    {
        return $this->bankAccounts;
    }

    public function addBankAccount(BankAccount $bankAccount): self
    {
        if (!$this->bankAccounts->contains($bankAccount)) {
            $this->bankAccounts->add($bankAccount);
            $bankAccount->setUser($this);
        }

        return $this;
    }

    public function removeBankAccount(BankAccount $bankAccount): self
    {
        if ($this->bankAccounts->removeElement($bankAccount)) {
            // set the owning side to null (unless already changed)
            if ($bankAccount->getUser() === $this) {
                $bankAccount->setUser(null);
            }
        }

        return $this;
    }

    public function getKycProfile(): ?KycProfile
    {
        return (
            $this->kycProfile ?? $this->setKycProfile(new KycProfile())->getKycProfile()
        );
    }

    public function setKycProfile(?KycProfile $kycProfile): self
    {
        $this->kycProfile = $kycProfile;

        return $this;
    }

    /**
     * @return Collection<int, KycReport>
     */
    public function getKycReports(): Collection
    {
        return $this->kycReports;
    }

    public function addKycReport(KycReport $kycReport): self
    {
        if (!$this->kycReports->contains($kycReport)) {
            $this->kycReports->add($kycReport);

            // $kycReport->setSubject($this);
        }

        return $this;
    }

    // public function removeKycReport(KycReport $kycReport): self
    // {
    //     if ($this->kycReports->removeElement($kycReport)) {
    //         // set the owning side to null (unless already changed)
    //         if ($kycReport->subject === $this) {
    //             $kycReport->setSubject(null);
    //         }
    //     }

    //     return $this;
    // }

    /**
     * @return Collection<int, KycReview>
     */
    public function getKycReviews(): Collection
    {
        return $this->kycReviews;
    }

    public function addKycReview(KycReview $kycReview): self
    {
        if (!$this->kycReviews->contains($kycReview)) {
            $this->kycReviews->add($kycReview);
            $kycReview->setSubject($this);
        }

        return $this;
    }

    public function removeKycReview(KycReview $kycReview): self
    {
        if ($this->kycReviews->removeElement($kycReview)) {
            // set the owning side to null (unless already changed)
            if ($kycReview->getSubject() === $this) {
                $kycReview->setSubject(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, KycReview>
     */
    public function getKycReviewsNeedingAction(): Collection
    {
        $criteria = Criteria::create()
            ->where(Criteria::expr()->in('status', [
                KycReviewStatus::PendingSubjectAction->value,
            ]))
            ->setMaxResults(1);
        /**
         * @var ArrayCollection|Collection $kycReviewsCollection
         */
        $kycReviewsCollection = $this->kycReviews;
        return $kycReviewsCollection->matching($criteria);
    }

    public function getOnboardingProfile(): OnboardingProfile
    {
        return (
            $this->onboardingProfile ?? $this->setOnboardingProfile(
                new OnboardingProfile(),
            )->getOnboardingProfile()
        );
    }

    public function setOnboardingProfile(?OnboardingProfile $onboardingProfile): static
    {
        // unset the owning side of the relation if necessary
        if ($onboardingProfile === null && $this->onboardingProfile !== null) {
            $this->onboardingProfile->setUser(null);
        }

        // set the owning side of the relation if necessary
        if ($onboardingProfile !== null && $onboardingProfile->getUser() !== $this) {
            $onboardingProfile->setUser($this);
        }

        $this->onboardingProfile = $onboardingProfile;

        return $this;
    }

    public function getScaEnrolledAt(): ?\DateTime
    {
        return $this->scaEnrolledAt;
    }

    public function setScaEnrolledAt(?\DateTime $scaEnrolledAt): static
    {
        $this->scaEnrolledAt = $scaEnrolledAt;

        return $this;
    }

    public function getScaStatus(): ScaStatus
    {
        return $this->scaStatus;
    }

    public function setScaStatus(ScaStatus $scaStatus): static
    {
        $this->scaStatus = $scaStatus;

        return $this;
    }

    public function getBankAccountsSyncedAt(): ?\DateTime
    {
        return $this->bankAccountsSyncedAt;
    }

    public function setBankAccountsSyncedAt(?\DateTime $bankAccountsSyncedAt): static
    {
        $this->bankAccountsSyncedAt = $bankAccountsSyncedAt;

        return $this;
    }

    /**
     * @return Collection<int, UserStatusLog>
     */
    public function getStatusLogs(): Collection
    {
        return $this->statusLogs;
    }

    public function addStatusLog(UserStatusLog $statusLog): static
    {
        if (!$this->statusLogs->contains($statusLog)) {
            $this->statusLogs->add($statusLog);
            $statusLog->setUser($this);
        }

        return $this;
    }

    public function removeStatusLog(UserStatusLog $statusLog): static
    {
        if ($this->statusLogs->removeElement($statusLog)) {
            // set the owning side to null (unless already changed)
            if ($statusLog->getUser() === $this) {
                $statusLog->setUser(null);
            }
        }

        return $this;
    }

    public function getCurrentStatus(): UserStatus
    {
        // This method should be just "getStatus"
        // But need to deprecate and remove legacy lifecycleStatus first
        return $this->statusLogs->isEmpty()
            ? UserStatus::Pending
            : $this->statusLogs->last()->getStatus();
    }

    public function getCurrentStatusLog(): ?UserStatusLog
    {
        return $this->statusLogs->isEmpty() ? null : $this->statusLogs->last();
    }

    /**
     * @return Collection<int, TradeOrder>
     */
    public function getTradeOrders(): Collection
    {
        return $this->tradeOrders;
    }

    public function addTradeOrder(TradeOrder $tradeOrder): static
    {
        if (!$this->tradeOrders->contains($tradeOrder)) {
            $this->tradeOrders->add($tradeOrder);
            $tradeOrder->setUser($this);
        }

        return $this;
    }

    public function removeTradeOrder(TradeOrder $tradeOrder): static
    {
        if ($this->tradeOrders->removeElement($tradeOrder)) {
            // set the owning side to null (unless already changed)
            if ($tradeOrder->getUser() === $this) {
                $tradeOrder->setUser(null);
            }
        }

        return $this;
    }
}
