framework:
    messenger:
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: 
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    auto_setup: false # This is effectively a default and can be overriden via the DSN
            failed: 'doctrine://default?queue_name=failed&auto_setup=0'
            sync: 'sync://'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
            'App\Message\DebugLog': async
            'App\Message\OrderBatchRun': async
            'App\Message\OrderBatchNotify': async

when@test:
   framework:
       messenger:
           transports:
               # replace with your transport name here (e.g., my_transport: 'in-memory://')
               # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
               async: 'in-memory://'
               failed: 'in-memory://'
