<?php

/**
 * Created by PhpStorm.
 * User: plok
 * Date: 28/02/17
 * Time: 09:55
 */

namespace App\Tests\Service\Email;

use App\Entity\Communication;
use App\Entity\User;
use App\Service\MailerService;
use App\Test\MailcatcherTestCase;

class MangoPayBankTransferTest extends MailcatcherTestCase
{
    /** @var MailerService $service */
    private $service;

    protected function setUp(): void
    {
        parent::setUp();
        $this->service = static::getContainer()->get(MailerService::class);
    }

    #[\PHPUnit\Framework\Attributes\Group('email')]
    public function testEmailBankwireTransferRequest(): void
    {
        // the count() method weirdly returns an array in the format [0 => [1 => $actualCount]]
        // Maybe using it wrong, but all type hints indicate it should just be a flat int
        $logEntriesBefore = $this->entityManager
            ->getRepository(Communication::class)
            ->count([]);

        // Get a non-top yielder user

        /** @var User $user */
        $user = $this->entityManager
            ->getRepository(User::class)
            ->findOneBy([
                'username' => self::USER_REGULAR,
            ]);

        // This is just for testing. Normally this is generated by mangopay
        $wireReference = 'testwireref';
        $type = 'testType';
        $ownerName = 'testOwnerName';
        $BIC = 'testBIC';
        $wireAmount = 'testAmount';

        $sent = $this->service->sendMail(
            $user,
            MailerService::TYPE_MANGOPAY_PAYIN_BANKTRANSFER,
            [
                'user' => $user,
                'wireReference' => $wireReference,
                'type' => $type,
                'ownerName' => $ownerName,
                'BIC' => $BIC,
                'Amount' => $wireAmount,
            ],
        );
        $this->assertEquals(1, $sent);
        $this->assertEquals(2, $this->getEmailCount());

        $message = $this->getMessages()[0];
        $messageContent = $this->getMessageInFormat($message->id);

        $this->assertEquals('Bankwire Transfer Details', $message->subject);
        $this->assertEquals('<noreply@yielders.co.uk>', $message->sender);
        $this->assertContains('<' . $user->getEmail() . '>', $message->recipients);

        $this->assertStringContainsString(
            'you will be making a bank transfer',
            $messageContent,
        );
        $this->assertStringContainsString($user->getFullName(), $messageContent);
        $this->assertStringContainsString($wireReference, $messageContent);
        $this->assertStringContainsString($BIC, $messageContent);
        $this->assertStringContainsString($ownerName, $messageContent);
        $this->assertStringContainsString($wireAmount, $messageContent);

        $logEntriesAfter = $this->entityManager
            ->getRepository(Communication::class)
            ->count([]);
        $this->assertEquals(2, $logEntriesAfter - $logEntriesBefore);

        /** @var Communication $communicationRecord */
        $communicationRecord = $this->entityManager
            ->getRepository(Communication::class)
            ->findOneBy([
                'subject' => 'Bankwire Transfer Details',
                'user' => $user->getId(),
            ]);
        $this->assertEquals($user->getEmail(), $communicationRecord->getRecipient());
        $this->assertEquals(
            'Bankwire Transfer Details',
            $communicationRecord->getSubject(),
        );

        // Check admin also receives the email
        $message = $this->getMessages()[1];
        $this->assertEquals('<noreply@yielders.co.uk>', $message->sender);
        $this->assertContains(
            '<' . self::ADMIN_EMAIL_ADDRESS . '>',
            $message->recipients,
        );
        $this->assertEquals('[Admin] Bankwire Transfer Details', $message->subject);
    }
}
