[program:messenger-consume]
command=php /workspace/bin/console messenger:consume async --time-limit=3600 --memory-limit=128M --limit=10
user=vscode
numprocs=2
startsecs=0
autostart=true
autorestart=true
startretries=10
process_name=%(program_name)s_%(process_num)02d